# PickM8 Configuration File
# This file controls ML model parameters and feature engineering settings

# Machine Learning Models Configuration
ml_models:
  default_type: "GaussianProcess"  # Options: RandomForest, GradientBoosting, SVM, GaussianProcess, MLP, AutoPartyEnsemble
  calibration_enabled: true
  calibration_method: "isotonic"  # Options: isotonic, sigmoid
  calibration_cv: 3
  
  # Feature Engineering Settings
  feature_engineering:
    enabled: true
    variance_threshold: 0.01  # Remove features with variance below this threshold
    use_importance_selection: true  # Use feature importance to select top features
    use_dimensionality_reduction: false  # Apply PCA/SVD
    normalize: true  # Normalize features before training
  
  # Model-specific parameters
  RandomForest:
    n_estimators: 200
    max_depth: null  # null means no limit
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    random_state: 42
    n_jobs: -1
  
  GradientBoosting:
    n_estimators: 150
    learning_rate: 0.1
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1
    subsample: 0.8
    random_state: 42
  
  SVM:
    C: 10.0
    gamma: "scale"
    kernel: "rbf"
    probability: true
    random_state: 42
  
  GaussianProcess:
    kernel: "Matern"  # Options: RBF, Matern
    optimize_kernel: true  # Optimize kernel hyperparameters
    n_restarts_optimizer: 10  # More restarts = better optimization
    random_state: 42
  
  MLP:
    hidden_layer_sizes: [200, 100]  # Two hidden layers
    learning_rate: "adaptive"
    alpha: 0.001
    max_iter: 500
    activation: "relu"
    solver: "adam"
    random_state: 42
  
  AutoPartyEnsemble:
    committee_size: 5  # Number of models in ensemble
    n_neurons: 1024
    hidden_layers: 3
    dropout: 0.3
    data_split: "bootstrap"
    learning_rate: 0.0001
    weight_decay: 0.01
    n_epochs: 150
    batch_size: 64

# Encoding Configuration
encoding:
  type: "sequential"  # Options: sequential, nominal, ordinal
  default_grades: ["A", "B", "C", "D"]


# Interaction Analysis Configuration
interactions:
  interaction_type: "plip"  # Options: plip, prolif
  ligand_name: "LIG"
  max_workers: 28  # Number of parallel workers
  plip_config:
    hydrogen_bonds: true
    hydrophobic_contacts: true
    pi_stacking: true
    salt_bridges: true
    halogen_bonds: true
  prolif_config:
    interactions: ["Hydrophobic", "HBDonor", "HBAcceptor", "PiStacking", "Anionic", "Cationic"]

# Pose Quality Configuration
pose_quality:
  enabled: true
  calculate_clashes: true
  calculate_strain: true
  max_workers: 28

# Processing Configuration
processing:
  fingerprint_config:
    compute_morgan: true
    compute_rdkit: false
    compute_mapchiral: false  # Set to true if MapChiral is installed
    morgan_radius: 2
    morgan_bits: 2048
    rdkit_bits: 2048
    mapchiral_max_radius: 2
    mapchiral_n_permutations: 2048