# PickM8 Configuration File
# This file controls ML model parameters and feature engineering settings

# Machine Learning Models Configuration
ml_models:
  default_type: "RandomForest"  # Options: RandomForest, GaussianProcess, LogisticAT
  
  # Feature Engineering Settings
  feature_engineering:
    enabled: true
    variance_threshold: 0.01  # Remove features with variance below this threshold
    use_importance_selection: true  # Use feature importance to select top features
    use_dimensionality_reduction: false  # Apply PCA/SVD
    normalize: true  # Normalize features before training
  
  # Model-specific parameters
  RandomForest:
    n_estimators: 200
    max_depth: null  # null means no limit
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    random_state: 42
    n_jobs: -1
  
  GaussianProcess:
    kernel: "Matern"  # Options: RBF, Matern
    optimize_kernel: true  # Optimize kernel hyperparameters
    n_restarts_optimizer: 10  # More restarts = better optimization
    random_state: 42
  
  LogisticAT:
    alpha: 1.0  # Regularization strength
    max_iter: 1000

# Encoding Configuration
encoding:
  type: "sequential"  # Options: sequential, one_hot, ordinal, ordinal_regression
  default_grades: ["A", "B", "C", "D"]
  
  # Encoding-specific settings
  ordinal_regression:
    grade_ranges:
      D: [0, 25]
      C: [25, 50]
      B: [50, 75]
      A: [75, 100]


# Interaction Analysis Configuration
interactions:
  interaction_type: "plip"  # Options: plip, prolif
  ligand_name: "LIG"
  max_workers: 28  # Number of parallel workers
  plip_config:
    hydrogen_bonds: true
    hydrophobic_contacts: true
    pi_stacking: true
    salt_bridges: true
    halogen_bonds: true
  prolif_config:
    interactions: ["Hydrophobic", "HBDonor", "HBAcceptor", "PiStacking", "Anionic", "Cationic"]

# Pose Quality Configuration
pose_quality:
  enabled: true
  calculate_clashes: true
  calculate_strain: true
  max_workers: 28

# Processing Configuration
processing:
  fingerprint_config:
    # Legacy fingerprint (kept for backward compatibility)
    compute_mapchiral: false  # Set to true if MapChiral is installed
    mapchiral_max_radius: 2
    mapchiral_n_permutations: 2048
    
    # scikit-fingerprints (main fingerprint implementation)
    compute_e3fp: false
    compute_ecfp: true  # Default enabled
    compute_electroshape: false
    compute_functional_groups: true  # Default enabled
    compute_maccs: true  # Default enabled  
    compute_pattern: false
    compute_pharmacophore: false
    
    # scikit-fingerprints parameters
    e3fp_params:
      fp_size: 2048
    
    ecfp_params:
      radius: 2
      fp_size: 2048
      include_chirality: true
    
    electroshape_params:
      partial_charge_model: "formal"  # Options: gasteiger, mmff94

    functional_groups_params:
      count: false
    
    maccs_params:
      count: false
    
    pattern_params:
      count: false
      fp_size: 2048
    
    pharmacophore_params:
      fp_size: 2048
  
  # GRADE Descriptor Configuration
  grade_config:
    enabled: false  # Set to true if CDPL/GRAIL is installed
    extended: false  # Use extended descriptors (GRAILXDescriptorCalculator)
    normalize_charges: false  # Normalize charges for pH 7
    max_workers: 8  # Number of parallel workers for computation