app:
  name: "PickM8"
  version: "0.1.0"
  
storage:
  session_dir: "data/sessions"
  defaults_dir: "data/defaults"
  user_models_dir: "data/user_models"
  
fingerprinting:
  default_type: "PLIP"  # Options: PLIP, PROLIF
  molecule_fp_type: "morgan"  # RDKit fingerprint type
  molecule_fp_size: 4096
  molecule_fp_radius: 2
  mapchiral_max_radius: 2
  mapchiral_n_permutations: 2048
  mapchiral_mapping: false
  
models:
  default_type: "ensemble"
  ensemble_size: 3
  max_epochs: 100
  learning_rate: 0.0001

ml_models:
  default_type: "RandomForest"
  calibration_enabled: true
  calibration_method: "isotonic"
  calibration_cv: 3
  
  RandomForest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    random_state: 42
    n_jobs: -1
    
  GradientBoosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    min_samples_split: 2
    min_samples_leaf: 1
    subsample: 1.0
    random_state: 42
    
  SVM:
    C: 1.0
    gamma: "scale"
    kernel: "rbf"
    probability: true
    random_state: 42
    
  GaussianProcess:
    kernel: "RBF"
    n_restarts_optimizer: 0
    random_state: 42
    
  MLP:
    hidden_layer_sizes: [100]
    learning_rate: "constant"
    alpha: 0.0001
    max_iter: 200
    activation: "relu"
    solver: "adam"
    random_state: 42

encoding:
  type: "sequential"  # Options: sequential, nominal, ordinal
  default_grades: ["A", "B", "C", "D", "F"]
  
visualization:
  mol_viewer_height: 600
  interaction_colors:
    "Hydrogen bond": "#4C4CFF"
    "Hydrophobic": "#FF7F00"
    "Pi-stacking": "#FF3333"
    "Halogen bond": "#7FFFFF"
    "Salt bridge": "#339933"
    "Water-bridged hydrogen bond": "#BFBFFF"