ml_models:
  default_type: 'RandomForest'
  calibration_enabled: true
  calibration_method: 'isotonic'
  calibration_cv: 3
  
  # PyTorch training parameters (shared)
  learning_rate: 0.0001
  weight_decay: 0.01
  n_epochs: 100
  batch_size: 128
  
  # Model-specific parameters
  RandomForest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: 'sqrt'
    random_state: 42
    n_jobs: -1
    
  GradientBoosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    min_samples_split: 2
    min_samples_leaf: 1
    subsample: 1.0
    random_state: 42
    
  SVM:
    C: 1.0
    gamma: 'scale'
    kernel: 'rbf'
    probability: true
    random_state: 42
    
  GaussianProcess:
    kernel: 'RBF'
    n_restarts_optimizer: 0
    random_state: 42
    
  MLP:
    hidden_layer_sizes: [100]
    learning_rate: 'constant'
    alpha: 0.0001
    max_iter: 200
    activation: 'relu'
    solver: 'adam'
    random_state: 42
    
  # AutoParty ensemble configuration
  AutoPartyEnsemble:
    committee_size: 3
    n_neurons: 1024
    hidden_layers: 2
    dropout: 0.2
    data_split: 'bootstrap'  # 'bootstrap' or 'full-split'