# PickM8 Configuration File
# This file controls ML model parameters and feature engineering settings

# Machine Learning Models Configuration
ml_models:
  default_type: "RandomForest"  # Options: RandomForest, GaussianProcess, LogisticAT
  calibration_enabled: true
  calibration_method: "isotonic"  # Options: isotonic, sigmoid
  calibration_cv: 3
  
  # Feature Engineering Settings
  feature_engineering:
    enabled: true
    variance_threshold: 0.01  # Remove features with variance below this threshold
    use_importance_selection: true  # Use feature importance to select top features
    use_dimensionality_reduction: false  # Apply PCA/SVD
    normalize: true  # Normalize features before training
  
  # Model-specific parameters
  RandomForest:
    n_estimators: 200
    max_depth: null  # null means no limit
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    random_state: 42
    n_jobs: -1
  
  GaussianProcess:
    kernel: "Matern"  # Options: RBF, Matern
    optimize_kernel: true  # Optimize kernel hyperparameters
    n_restarts_optimizer: 10  # More restarts = better optimization
    random_state: 42
  
  LogisticAT:
    alpha: 1.0  # Regularization strength
    max_iter: 1000
    random_state: 42

# Encoding Configuration
encoding:
  type: "sequential"  # Options: sequential, one_hot, ordinal, ordinal_regression
  default_grades: ["A", "B", "C", "D"]
  
  # Encoding-specific settings
  ordinal_regression:
    grade_ranges:
      D: [0, 25]
      C: [25, 50]
      B: [50, 75]
      A: [75, 100]


# Interaction Analysis Configuration
interactions:
  interaction_type: "plip"  # Options: plip, prolif
  ligand_name: "LIG"
  max_workers: 28  # Number of parallel workers
  plip_config:
    hydrogen_bonds: true
    hydrophobic_contacts: true
    pi_stacking: true
    salt_bridges: true
    halogen_bonds: true
  prolif_config:
    interactions: ["Hydrophobic", "HBDonor", "HBAcceptor", "PiStacking", "Anionic", "Cationic"]

# Pose Quality Configuration
pose_quality:
  enabled: true
  calculate_clashes: true
  calculate_strain: true
  max_workers: 28

# Processing Configuration
processing:
  fingerprint_config:
    compute_morgan: true
    compute_rdkit: false
    compute_mapchiral: false  # Set to true if MapChiral is installed
    morgan_radius: 2
    morgan_bits: 2048
    rdkit_bits: 2048
    mapchiral_max_radius: 2
    mapchiral_n_permutations: 2048